### PR TITLE
Updated to louvain 0.7.0 and corrected build script

### PR DESCRIPTION
**Pull request by vtraag**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This renders PR #8 obsolete. I have added myself as a maintainer for the package.

### CODE REVIEW

**Comment by vtraag** [comment]
@conda-forge-admin, please rerender

**Comment by vtraag** [comment]
Ping @vgauthier, would you be able to review this PR?

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
@vgauthier Can you review this?

@conda-forge/core Would someone be interested in updating and merging this? There's a competing PR on Bioconda to add this there already (I obviously want to avoid doing that).

**Comment by beckermr** [comment]
We need to solve the merge conflicts then this can be merged.

**Comment by mariusvniekerk** [comment]
@yihming can this one be closed now?

**Comment by yihming** [comment]
Hi @mariusvniekerk . I think so, but I'm not the author of this pull request. Not sure if I'm the appropriate person to be reached.

**Comment by vtraag** [comment]
AFAIK we can close this. I will add Windows support at some later time.

**Pull request closed without merging**
